@echo off
echo.
echo ========================================
echo Firebase Configuration Setup Helper
echo ========================================
echo.
echo This script will create the .env.local file for you.
echo.
echo You'll need your Firebase credentials from:
echo https://console.firebase.google.com/
echo.
pause
echo.

set /p apiKey="Enter FIREBASE_API_KEY: "
set /p authDomain="Enter AUTH_DOMAIN (e.g., your-project.firebaseapp.com): "
set /p projectId="Enter PROJECT_ID: "
set /p storageBucket="Enter STORAGE_BUCKET (e.g., your-project.appspot.com): "
set /p messagingSenderId="Enter MESSAGING_SENDER_ID: "
set /p appId="Enter APP_ID: "

echo.
echo Creating .env.local file...
echo.

(
echo # Firebase Configuration
echo # Generated by create-env.bat
echo.
echo VITE_FIREBASE_API_KEY=%apiKey%
echo VITE_FIREBASE_AUTH_DOMAIN=%authDomain%
echo VITE_FIREBASE_PROJECT_ID=%projectId%
echo VITE_FIREBASE_STORAGE_BUCKET=%storageBucket%
echo VITE_FIREBASE_MESSAGING_SENDER_ID=%messagingSenderId%
echo VITE_FIREBASE_APP_ID=%appId%
) > .env.local

echo.
echo ✅ .env.local file created successfully!
echo.
echo Next steps:
echo 1. Restart your dev server (Ctrl+C, then npm run dev)
echo 2. Open http://localhost:5174/ in your browser
echo 3. Test Google Sign-In
echo.
pause

